### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by ShaneFromFargo** [ADSB-One/api#2]
I'm having issues calling this API from my command line. It works fine on Postman but when trying to call it from the command line I get met with the following error.

C:\Dev>curl -v https://api.adsb.one/v2/mil
*   Trying 104.26.4.4:443...
* Connected to api.adsb.one (104.26.4.4) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
* Closing connection 0
* schannel: shutting down SSL/TLS connection with api.adsb.one port 443
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.

I've tried this on both Mac and PC. I've also tried on different networks, and I am always running into some sort of SSL error.

**Comment by Huusky** [comment]
@ShaneFromFargo Please give this another try. CF was enforcing TLS v1.3 and has since been changed to v1.2.
